### PR TITLE
Fixes for future types for fallback promise future query.

### PR DESCRIPTION
**Pull request by LeeHowes**
Issue #93 

Change from std::future/std::promise (leftover from when this was a separate paper) to std::standard_semi_future/std::standard_promise.

### CODE REVIEW

**Comment by dhollman** [comment]
I guess the way we've written the new requirements on `ThenExecutor`, the association of a closure before type erasure is no longer necessary.

**Comment by dhollman** [comment]
This change also makes `standard_promise` and `standard_continuable_future` into *de facto* type-erasing wrappers.  Are we okay with that?

**Comment by dhollman** [comment]
@LeeHowes We can do something slightly different here and address #97 also.  What do you think?

**Comment by LeeHowes** [comment]
Merging and we can build on it.

**Pull request merged**
