### PR TITLE
Fix refs and dfns

### PR DESCRIPTION
**Pull request by griwes**
The `shared future` term has been overloaded and that was making bikeshed confused - and I think it wasn't making much sense to confuse the ownership and the concept.

I'm open to other solutions to the problem this tries to fix, but @brycelelbach agrees that this general direction works.

Also removed another duplicate dfn and actually defined what a status is.

### CODE REVIEW

**Comment by griwes** [comment]
@brycelelbach @LeeHowes @dhollman please review

**Comment by dhollman** [comment]
This was already fixed in #105.



Thanks,

David


On May 6, 2018 at 8:10:54 PM, Michał Dominiak (notifications@github.com<mailto:notifications@github.com>) wrote:

The shared future term has been overloaded and that was making bikeshed confused - and I think it wasn't making much sense to confuse the ownership and the concept.

I'm open to other solutions to the problem this tries to fix, but @brycelelbach<https://github.com/brycelelbach> agrees that this general direction works.

Also removed another duplicate dfn and actually defined what a status is.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/executors/futures/pull/108

Commit Summary

  *   Fix the erroneous defs and refs.
  *   Add gitignore for the generated html file.

File Changes

  *   A .gitignore<https://github.com/executors/futures/pull/108/files#diff-0> (1)
  *   M futures.bs<https://github.com/executors/futures/pull/108/files#diff-1> (14)

Patch Links:

  *   https://github.com/executors/futures/pull/108.patch
  *   https://github.com/executors/futures/pull/108.diff

**Comment by griwes** [comment]
Ah yes, some of it has been.

#105 doesn't fix `status`, though, plus it solves the shared future problem differently, still retaining what I see to be confusing overloading of the term (for the concept, and then for semantics, if that makes sense). In one place we have `SharedFuture` and `ContinuableFuture`, but in the other place we have `unique future` and `shared future`, with just one of those being a separate concept. I would like to fix that the way I proposed here.

Will rebase on top of #105 when that's merged.

**Comment by griwes** [comment]
Rebased and actually make sure that a `SharedFuture` is understood to be a non-uniquely owned future.

@LeeHowes sanity check on the terminology please?

**Pull request merged**
